### ISSUE TITLE
Fix initial setup issues

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/braingdx#127]
At the moment, the following problems occur after initial setup (and following the guide 1:1):

- copy-pasting the gradle version does not work because single quotes are not allowed in `build.gradle` with version interpolation
- "just" adding **braingdx** does not work. We still require the `freetype` dependency
- **box2dlights** is trickier since people can override mandatory version `1.5+`
- `EmptyGameAssetLoader` does not exist?

**Comment by bitbrain** [comment]
@born2snipe if you have suggestions or remarks, let me know. I want to make the initial setup flow as simple as possible.

**Comment by born2snipe** [comment]
I would suggest creating another JAR at least for "desktop" projects that will include the following jars:
 - com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion
 - com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop
 - com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop
 - com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop

The idea being you just add the "core" and "desktop" JARs and you will be up in running quickly.

If you do not like that idea you could always make a PR to the libgdx repo to add your framework as an available extension when using the project setup tool. I believe you only need to add your artifacts to this [file](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml). That would allow you to easily add the JARs to the appropriate modules of a new project.

**Comment by bitbrain** [comment]
@born2snipe I like this idea. Rather than adding **braingdx** to your **libgdx** project, you actively decide to go with this framework. (yes, you still have to generate the project with libgdx but with minimum dependencies. Instead, just add **braingdx** and it will do the rest.

**Comment by bitbrain** [comment]
**Freetype** and **box2dlights** now comes with **braingdx** `0.2.13`. When generating a **libgdx** project make sure to still include **box2d** since we rely on the box2d natives (android, desktop, iOS respectively).
