### ISSUE TITLE
buildbreak (ssl certificate, box2dlights)

### ISSUE THREAD

**Issue by gterminator** [bitbrain/braingdx#69]
Hi,
the new server requires to import a certificate into the keystore, otherwise you will get a "peer not authenticated".

In the next step i get the following at building with gradle:

**gradlew desktop:build**
Configuration on demand is an incubating feature.
:core:compileJava
Download https://nexus.k40s.net/repository/braingdx/de/bitbrain/braingdx/braingdx-core/0.0.1/braingdx-core-0.0.1.pom
Download https://nexus.k40s.net/repository/braingdx/de/bitbrain/braingdx/0.0.1/braingdx-0.0.1.pom

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':core:compile'.
> Could not find com.github.libgdx:box2dlights:box2dlights-2.0-dev-SNAPSHOT.
  Searched in the following locations:
      file:/C:/Users/Gterminator/.m2/repository/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/maven-metadata.xml
      file:/C:/Users/Gterminator/.m2/repository/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/box2dlights-box2dlights-2.0-dev-SNAPSHOT.pom
      file:/C:/Users/Gterminator/.m2/repository/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/box2dlights-box2dlights-2.0-dev-SNAPSHOT.jar
      https://repo1.maven.org/maven2/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/box2dlights-box2dlights-2.0-dev-SNAPSHOT.pom
      https://repo1.maven.org/maven2/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/box2dlights-box2dlights-2.0-dev-SNAPSHOT.jar
      https://oss.sonatype.org/content/repositories/snapshots/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/maven-metadata.xml
      https://oss.sonatype.org/content/repositories/snapshots/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/box2dlights-box2dlights-2.0-dev-SNAPSHOT.pom
      https://oss.sonatype.org/content/repositories/snapshots/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/box2dlights-box2dlights-2.0-dev-SNAPSHOT.jar
      https://oss.sonatype.org/content/repositories/releases/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/maven-metadata.xml
      https://oss.sonatype.org/content/repositories/releases/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/box2dlights-box2dlights-2.0-dev-SNAPSHOT.pom
      https://oss.sonatype.org/content/repositories/releases/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/box2dlights-box2dlights-2.0-dev-SNAPSHOT.jar
      https://nexus.k40s.net/repository/braingdx/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/maven-metadata.xml
      https://nexus.k40s.net/repository/braingdx/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/box2dlights-box2dlights-2.0-dev-SNAPSHOT.pom
      https://nexus.k40s.net/repository/braingdx/com/github/libgdx/box2dlights/box2dlights-2.0-dev-SNAPSHOT/box2dlights-box2dlights-2.0-dev-SNAPSHOT.jar
  Required by:
      beansjam-2017:core:1.0 > de.bitbrain.braingdx:braingdx-core:0.0.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.572 secs

should the box2dlights from libgdx now in the project?

regards,
Max

**Comment by bitbrain** [comment]
Hey,

the `box2dlights-2.0-dev` must still be fetched from the stupid JitPack.io repository right now. Today I will transfer the modified artifacts into the new maven repository as well, so you should not get an error there anymore. I will close this issue as soon this is resolved.

Thanks for reporting!

If you are wondering why we suffer all this pain: it's (as you already know) because of [this unreleased commit in 1.5](https://github.com/libgdx/box2dlights/commit/ee03de49a25808440a86d20860ce1b828f332b22) (which is not released yet).

Regarding your SSL issue: does it still happen? There were serious issues with https://letsencrypt.org the last days and by now those issues should be resolved (at least for me it works).  @lfuelling do you know about this "peer not authenticated" issue?

**Comment by lfuelling** [comment]
`box2dlights` is not on the nexus. As a possible workaround, I've put the braingdx repo in the public group which also proxies jcenter, maven.apache.org and the google m2 repo. 

Please try using `https://nexus.k40s.net/repository/maven-public/` as repository for *all* of the dependencies and report back to me if it fixes this issue.

**Comment by bitbrain** [comment]
@lfuelling no, `beansjam-2017` still used `Jitpack.io` to retrieve dependencies but we want to move away from that because it behaves strangely when using a multi-module project. `box2dlights` is still on `Jitpack.io` but I want to move it onto your nexus today as well.

**Comment by bitbrain** [comment]
@gterminator quick question: is the build log you appended from a new libgdx gradle project or did you try to build `braingdx` locally via Maven?

**Comment by lfuelling** [comment]
@bitbrain looks like it's your beansjam project:

```
Required by:
beansjam-2017:core:1.0 > de.bitbrain.braingdx:braingdx-core:0.0.1
```

**Comment by bitbrain** [comment]
Ah, okay then the stacktrace makes sense. `box2dlights` is NOT in the new nexus but still on `JitPack.io`. So right now we need both repositories. This will change in the near future.

**Comment by gterminator** [comment]
Hi, i fixed the ssl issue by importing the certificates into the java keystore.

regards
Max

**Comment by bitbrain** [comment]
Fixed now: https://github.com/bitbrain/beansjam-2017/commit/bff1dd53d941ef6ccfee868c63a9dafce09cf832 please rebuild with `--refresh-dependencies` flag.

**Comment by lfuelling** [comment]
@gterminator which one did you have to install? The repository certificate was signed using Let'sEncrypt.

@bitbrain maven-public now also proxies [jitpack.io](https://jitpack.io)

**Comment by bitbrain** [comment]
OMG THANKS!!
